name: venv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cudatoolkit=11.3.1
  - cudnn=8.2.1.32
  - ffmpeg=4.3
  - filelock=3.17.0
  - freetype=2.12.1
  - git=2.45.2
  - intel-openmp=2025.0.0
  - jinja2=3.1.6
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.10
  - libffi=3.4.6
  - libflac=1.3.4
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.43
  - libsndfile=1.0.31
  - libsqlite=3.49.1
  - libtiff=4.3.0
  - libuv=1.50.0
  - libvorbis=1.3.7
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxml2=2.12.7
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - networkx=3.2
  - olefile=0.47
  - openjpeg=2.5.0
  - openssl=1.1.1w
  - pillow=8.4.0
  - pip=21.3.1
  - pthreads-win32=2.9.1
  - python=3.9.9
  - python_abi=3.9
  - pytorch-mutex=1.0
  - setuptools=75.8.2
  - sqlite=3.49.1
  - tbb=2021.13.0
  - tk=8.6.13
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wheel=0.35.1
  - xz=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - aniso8601==10.0.0
      - annotated-types==0.7.0
      - argparse==1.4.0
      - astunparse==1.6.3
      - attrs==25.1.0
      - audioread==3.0.1
      - beautifulsoup4==4.13.3
      - blinker==1.9.0
      - blis==1.2.0
      - catalogue==2.0.10
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - clang==5.0
      - click==8.1.8
      - cloudpathlib==0.21.0
      - cmudict==1.0.32
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - confection==0.1.5
      - curated-tokenizers==0.0.9
      - curated-transformers==0.1.1
      - cycler==0.12.1
      - cymem==2.0.11
      - cython==3.0.12
      - decorator==5.2.1
      - deepface==0.0.93
      - dtw-python==1.5.3
      - en-core-web-sm==3.8.0
      - errant==3.0.0
      - fire==0.7.0
      - flask==3.1.0
      - flask-cors==5.0.1
      - flask-restful==0.3.10
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - fsspec==2024.6.1
      - fuzzywuzzy==0.18.0
      - gast==0.6.0
      - gdown==5.2.0
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - gunicorn==23.0.0
      - h5py==3.13.0
      - huggingface-hub==0.29.2
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - keras==3.9.0
      - kiwisolver==1.4.7
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - levenshtein==0.27.1
      - libclang==18.1.1
      - librosa==0.10.2.post1
      - llvmlite==0.43.0
      - marisa-trie==1.2.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.5.1
      - mdurl==0.1.2
      - mediapipe==0.10.21
      - ml-dtypes==0.5.1
      - more-itertools==10.6.0
      - msgpack==1.1.0
      - mtcnn==0.1.1
      - murmurhash==1.0.12
      - my-voice-analysis==0.7
      - namex==0.0.8
      - numba==0.60.0
      - numpy==1.26.4
      - onnxruntime==1.19.2
      - openai-whisper==20240930
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.14.1
      - packaging==24.2
      - pandas==1.3.5
      - platformdirs==4.3.6
      - pooch==1.8.2
      - praat-parselmouth==0.4.5
      - preshed==3.0.9
      - protobuf==4.25.6
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pyphen==0.17.2
      - pyreadline3==3.5.4
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-levenshtein==0.27.1
      - pytz==2025.1
      - pyyaml==6.0
      - rapidfuzz==3.12.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - resampy==0.4.3
      - retina-face==0.0.17
      - rich==13.9.4
      - rpds-py==0.23.1
      - safetensors==0.5.3
      - scikit-learn==1.0.2
      - scipy==1.13.1
      - seaborn==0.11.2
      - sentence-transformers==3.4.1
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - silero-vad==5.1.2
      - six==1.17.0
      - smart-open==7.1.0
      - sounddevice==0.5.1
      - soundfile==0.13.1
      - soupsieve==2.6
      - soxr==0.5.0.post1
      - spacy==3.8.3
      - spacy-curated-transformers==0.3.0
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - speechrecognition==3.14.1
      - srsly==2.5.1
      - srt==3.5.3
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.5.0
      - textstat==0.7.5
      - tf-keras==2.19.0
      - thinc==8.3.4
      - threadpoolctl==3.5.0
      - tiktoken==0.9.0
      - tokenizers==0.21.0
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.62.3
      - transformers==4.49.0
      - typer==0.15.2
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - vosk==0.3.45
      - wasabi==1.1.3
      - weasel==0.4.1
      - websockets==15.0.1
      - werkzeug==3.1.3
      - whisper==1.1.10
      - whisper-timestamped==1.15.8
      - wrapt==1.17.2
      - zipp==3.21.0
      - "--editable=git+https://github.com/PrithivirajDamodaran/Gramformer.git#egg=gramformer"
prefix: C:\Users\INDRANEEL KVS\.conda\envs\venv
